
# Name:
# Description:

# dotenv (below) gets env from ~/.env (load b4 import openai)
from dotenv import load_dotenv
load_dotenv()
import os
import openai

#####
# Create a chat completion prompt
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",  # or another model like "text-davinci-004"
    messages=[
        {"role": "system", "content": "You are a knowledgeable sports enthusiast."},
        {"role": "user", "content": "Hey, what do you think about the Winnipeg Jets?"},
        {"role": "assistant", "content": "The Winnipeg Jets have been performing quite well this season. They have a strong offense."},
        {"role": "user", "content": "Yeah, their offense is great, but do you think their defense is good enough to make a deep playoff run?"},
        # The assistant's response will be generated by the model
    ]
)

# Print the response
print(response['choices'][0]['message']['content'])
